version: '3.9'

services:
  instrugo-test-database:
    container_name: instrugo-test-database
    image: postgres:14.2-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: instrugo-test-database
